description: enumerate species counterpoint with sbv

dependencies:
  - base
  - sbv
  - lens
  - lens-action
  - tidal
  - containers
  - tidal-core
  - split

library:
  source-dirs:
    - lib
  default-extensions:
    - BlockArguments
    - DisambiguateRecordFields
    - DuplicateRecordFields
    - NamedFieldPuns
    - RecordWildCards
    - TupleSections
    - TypeApplications
    - ViewPatterns
